export const courseInfo = [{
        name: "Python/Django",
        description: "Django is a Python-based web application framework that is free and open source. A framework is simply a collection of modules that facilitate development. They're grouped together and allow you to build apps or websites from scratch rather than starting from scratch.",
        price: 20000,
        tutor: "ABC",
        img: "https://swapps.com/wp-content/uploads/2019/04/django-faster-1024x576.jpg",
        link: "https://www.djangoproject.com",
    },
    {
        name: "MERN",
        description: "MERN stands for MongoDB, Express, React, Node, after the four key technologies that make up the stack. MongoDB — document database. Express(.js) — Node.js web framework. React(.js) — a client-side JavaScript framework. Node(.js) — the premier JavaScript web server.",
        price: 22000,
        link: "https://www.mongodb.com/languages/mern-stack-tutorial#:~:text=the%20Back%20End-,What%20is%20the%20MERN%20Stack%3F,variants%20of%20the%20MEAN%20stack.",
        tutor: "Arun Sir",
        img: "https://cdn.mobcoder.com/assets/blog_images/mern-stack/Mern-1_11zon.webp",
    },
    {
        name: "Python-With-Ai",
        description: "Python is a key part of AI programming languages due to the fact that it has good frameworks, such as scikit-learn-Machine Learning in Python that meets almost all requirements in this area as well as D3. js data-driven documents JS. It is among the most efficient and user-friendly tools to visualize",
        price: 24000,
        tutor: "LOP",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png",
        link: "https://www.wolfram.com/language/fast-introduction-for-programmers/en/?compare=python&src=google&1701&gclid=Cj0KCQjwl8anBhCFARIsAKbbpyR9djH_OSXiSh3xSG221w6PUwDiRfFBM5FphhOVwOs79eqpck_qJ1UaAk0wEALw_wcB",
    },
    {
        name: "Graphic-Design",
        description: "Graphic design is a craft where professionals create visual content to communicate messages. By applying visual hierarchy and page layout techniques, designers use typography and pictures to meet users' specific needs and focus on the logic of displaying elements in interactive designs, to optimize the user experience.",
        price: 15000,
        tutor: "ATH",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCUuHLuWT3YfMomv-m1NuUR-8C35mLD9eXAQ&usqp=CAU",
        link: "https://www.youtube.com/watch?v=-a0bgFY1onU&themeRefresh=1",
    },
    {
        name: "Flutter",
        description: "Flutter is Google's portable UI toolkit for crafting beautiful, natively compiled applications for mobile, web, and desktop from a single codebase. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source.",
        price: 21500,
        tutor: "QRT",
        img: "https://www.mindinventory.com/blog/wp-content/uploads/2022/10/flutter-3.png",
        link: "https://flutter.dev/?gclid=Cj0KCQjwl8anBhCFARIsAKbbpyQ53aX3lJjkEBQKQHyb47TIbx5GmGfYLqaVIdcVQ8t7VInyUjWQ3xEaAl3QEALw_wcB&gclsrc=aw.ds",
    },
    {
        name: "React_Native",
        description: "React is a JavaScript-based UI development library. Facebook and an open-source developer community run it. Although React is a library rather than a language, it is widely used in web development. The library first appeared in May 2013 and is now one of the most commonly used frontend libraries for web development.",
        price: 22000,
        tutor: "XYZ",
        link: "https://reactnative.dev",
        img: "https://crowdbotics.ghost.io/content/images/2020/10/React-Native-Featured-Image.png",
    },

];